import { Product } from "./types/Product";

export const sampleProducts: Product[] = [
  {
    name: "Camiseta Nike Slim",
    slug: "camiseta-nike-slim",
    category: "Camisetas",
    image: "../images/p1.jpg",
    price: 120,
    countInStock: 10,
    brand: "Nike",
    rating: 4.5,
    numReviews: 10,
    description: "camiseta de alta qualidade",
  },
  {
    name: "Camiseta Nike Slim",
    slug: "camiseta-nik-slim",
    category: "Camisetas",
    image: "../images/p2.jpg",
    price: 120,
    countInStock: 10,
    brand: "Nike",
    rating: 4.5,
    numReviews: 10,
    description: "camiseta de alta qualidade",
  },
  {
    name: "Camiseta Nike Slim",
    slug: "camiseta-nke-slim",
    category: "Camisetas",
    image: "../images/p3.jpg",
    price: 120,
    countInStock: 10,
    brand: "Nike",
    rating: 4.5,
    numReviews: 10,
    description: "camiseta de alta qualidade",
  },
  {
    name: "Camiseta Nike Slim",
    slug: "camista-nike-slim",
    category: "Camisetas",
    image: "../images/p4.jpg",
    price: 120,
    countInStock: 10,
    brand: "Nike",
    rating: 4.5,
    numReviews: 10,
    description: "camiseta de alta qualidade",
  },
];
